@startuml
title snowbridge Tooling Integrations
left to right direction
skinparam shadowing false
skinparam defaultFontName Monospace
skinparam componentStyle rectangle
skinparam linetype ortho
rectangle ".github/workflows/ci.yml\n4 detected tools" as source_github_workflows_ci_yml #E0F2FE
rectangle ".github/workflows/secret-scan.yml\n2 detected tools" as source_github_workflows_secret_scan_yml #E0F2FE
rectangle "config/access/tailscale/tailscale-subnet-router.example.sh\n1 detected tool" as source_config_access_tailscale_tailscale_subnet_router_example_sh #E0F2FE
rectangle "config/access/tailscale/tailscale-subnet-router.local.sh\n1 detected tool" as source_config_access_tailscale_tailscale_subnet_router_local_sh #E0F2FE
rectangle "config/network/networkmanager-static-ip.example.sh\n2 detected tools" as source_config_network_networkmanager_static_ip_example_sh #E0F2FE
rectangle "config/network/networkmanager-static-ip.local.sh\n2 detected tools" as source_config_network_networkmanager_static_ip_local_sh #E0F2FE
rectangle "scripts/build_filebrowser_fork_image.sh\n4 detected tools" as source_scripts_build_filebrowser_fork_image_sh #E0F2FE
rectangle "scripts/debug_private_access.sh\n12 detected tools" as source_scripts_debug_private_access_sh #E0F2FE
rectangle "scripts/deploy_filebrowser_fork_image.sh\n10 detected tools" as source_scripts_deploy_filebrowser_fork_image_sh #E0F2FE
rectangle "scripts/remount_luks_share.sh\n3 detected tools" as source_scripts_remount_luks_share_sh #E0F2FE
rectangle "scripts/run_tachometer_profile.sh\n3 detected tools" as source_scripts_run_tachometer_profile_sh #E0F2FE
rectangle "scripts/setup_caddy_filebrowser.sh\n32 detected tools" as source_scripts_setup_caddy_filebrowser_sh #E0F2FE
rectangle "scripts/setup_filebrowser_fork_workspace.sh\n7 detected tools" as source_scripts_setup_filebrowser_fork_workspace_sh #E0F2FE
rectangle "scripts/setup_wireguard_endpoint_monitor.sh\n3 detected tools" as source_scripts_setup_wireguard_endpoint_monitor_sh #E0F2FE
rectangle "scripts/start_snowbridge.sh\n8 detected tools" as source_scripts_start_snowbridge_sh #E0F2FE
rectangle "vendor/filebrowser-upstream/Dockerfile\n8 detected tools" as source_vendor_filebrowser_upstream_dockerfile #E0F2FE
rectangle "vendor/filebrowser-upstream/Dockerfile.s6\n5 detected tools" as source_vendor_filebrowser_upstream_dockerfile_s6 #E0F2FE
rectangle "vendor/filebrowser-upstream/Taskfile.yml\n7 detected tools" as source_vendor_filebrowser_upstream_taskfile_yml #E0F2FE
rectangle "vendor/filebrowser-upstream/compose.yaml\n1 detected tool" as source_vendor_filebrowser_upstream_compose_yaml #E0F2FE
rectangle "vendor/filebrowser-upstream/docker/alpine/healthcheck.sh\n6 detected tools" as source_vendor_filebrowser_upstream_docker_alpine_healthcheck_sh #E0F2FE
rectangle "vendor/filebrowser-upstream/docker/alpine/init.sh\n1 detected tool" as source_vendor_filebrowser_upstream_docker_alpine_init_sh #E0F2FE
rectangle "vendor/filebrowser-upstream/docker/common/healthcheck.sh\n1 detected tool" as source_vendor_filebrowser_upstream_docker_common_healthcheck_sh #E0F2FE
rectangle "vendor/filebrowser-upstream/docker/s6/custom-cont-init.d/20-config\n2 detected tools" as source_vendor_filebrowser_upstream_docker_s6_custom_cont_init_d_20_config #E0F2FE
rectangle "vendor/filebrowser-upstream/docker/s6/etc/services.d/filebrowser/run\n0 detected tools" as source_vendor_filebrowser_upstream_docker_s6_etc_services_d_filebrowser_run #E0F2FE
rectangle "vendor/filebrowser-upstream/www/Dockerfile\n2 detected tools" as source_vendor_filebrowser_upstream_www_dockerfile #E0F2FE
cloud "!in_global" as tool_in_global #FEF3C7
cloud "(command_exists" as tool_command_exists #FEF3C7
cloud "(major" as tool_major #FEF3C7
cloud "2[0-9]" as tool_tool_2_0_9 #FEF3C7
cloud "3[0-1])." as tool_tool_3_0_1 #FEF3C7
cloud "443" as tool_tool_443 #FEF3C7
cloud "445" as tool_tool_445 #FEF3C7
cloud "80" as tool_tool_80 #FEF3C7
cloud "^[[:space:]]*" as tool_space #FEF3C7
cloud "^[[:space:]]+" as tool_space_2 #FEF3C7
cloud "actions/checkout" as tool_actions_checkout #FEF3C7
cloud "actions/setup-python" as tool_actions_setup_python #FEF3C7
cloud "addgroup" as tool_addgroup #FEF3C7
cloud "adduser" as tool_adduser #FEF3C7
cloud "apk" as tool_apk #FEF3C7
cloud "apt-get" as tool_apt_get #FEF3C7
cloud "args+=(" as tool_args #FEF3C7
cloud "args+=(--container-tool" as tool_args_container_tool #FEF3C7
cloud "awk" as tool_awk #FEF3C7
cloud "bash" as tool_bash #FEF3C7
cloud "cat" as tool_cat #FEF3C7
cloud "chmod" as tool_chmod #FEF3C7
cloud "chown" as tool_chown #FEF3C7
cloud "cli" as tool_cli #FEF3C7
cloud "cp" as tool_cp #FEF3C7
cloud "dig" as tool_dig #FEF3C7
cloud "dnf" as tool_dnf #FEF3C7
cloud "docker" as tool_docker #FEF3C7
cloud "docker compose" as tool_docker_compose #FEF3C7
cloud "docker-compose" as tool_docker_compose_2 #FEF3C7
cloud "git" as tool_git #FEF3C7
cloud "gitleaks/gitleaks-action" as tool_gitleaks_gitleaks_action #FEF3C7
cloud "go" as tool_go #FEF3C7
cloud "golang-go" as tool_golang_go #FEF3C7
cloud "grep" as tool_grep #FEF3C7
cloud "host" as tool_host #FEF3C7
cloud "i" as tool_i #FEF3C7
cloud "id" as tool_id #FEF3C7
cloud "in_global" as tool_in_global_2 #FEF3C7
cloud "install" as tool_install #FEF3C7
cloud "ip" as tool_ip #FEF3C7
cloud "ipv6.method" as tool_ipv6_method #FEF3C7
cloud "ln" as tool_ln #FEF3C7
cloud "mapfile" as tool_mapfile #FEF3C7
cloud "minor" as tool_minor #FEF3C7
cloud "mkdir" as tool_mkdir #FEF3C7
cloud "mount" as tool_mount #FEF3C7
cloud "mv" as tool_mv #FEF3C7
cloud "next" as tool_next #FEF3C7
cloud "nmcli" as tool_nmcli #FEF3C7
cloud "node" as tool_node #FEF3C7
cloud "nordvpn" as tool_nordvpn #FEF3C7
cloud "pip" as tool_pip #FEF3C7
cloud "pnpm" as tool_pnpm #FEF3C7
cloud "podman" as tool_podman #FEF3C7
cloud "podman-compose" as tool_podman_compose #FEF3C7
cloud "pre-commit" as tool_pre_commit #FEF3C7
cloud "print" as tool_print #FEF3C7
cloud "private-vpn" as tool_private_vpn #FEF3C7
cloud "private-vpn-mtls" as tool_private_vpn_mtls #FEF3C7
cloud "public" as tool_public #FEF3C7
cloud "rm" as tool_rm #FEF3C7
cloud "run" as tool_run #FEF3C7
cloud "sed" as tool_sed #FEF3C7
cloud "setcap" as tool_setcap #FEF3C7
cloud "settings.json" as tool_settings_json #FEF3C7
cloud "sh" as tool_sh #FEF3C7
cloud "site" as tool_site #FEF3C7
cloud "split(site," as tool_split_site #FEF3C7
cloud "srv" as tool_srv #FEF3C7
cloud "summarize" as tool_summarize #FEF3C7
cloud "systemctl" as tool_systemctl #FEF3C7
cloud "tachometer" as tool_tachometer #FEF3C7
cloud "tr" as tool_tr #FEF3C7
cloud "umount" as tool_umount #FEF3C7
cloud "up" as tool_up #FEF3C7
cloud "update-ca-certificates" as tool_update_ca_certificates #FEF3C7
cloud "update-ca-trust" as tool_update_ca_trust #FEF3C7
cloud "updated" as tool_updated #FEF3C7
cloud "wg" as tool_wg #FEF3C7
cloud "wget" as tool_wget #FEF3C7
cloud "yum" as tool_yum #FEF3C7
source_github_workflows_ci_yml --> tool_actions_checkout
source_github_workflows_ci_yml --> tool_actions_setup_python
source_github_workflows_ci_yml --> tool_pip
source_github_workflows_ci_yml --> tool_pre_commit
source_github_workflows_secret_scan_yml --> tool_actions_checkout
source_github_workflows_secret_scan_yml --> tool_gitleaks_gitleaks_action
source_config_access_tailscale_tailscale_subnet_router_example_sh --> tool_systemctl
source_config_access_tailscale_tailscale_subnet_router_local_sh --> tool_systemctl
source_config_network_networkmanager_static_ip_example_sh --> tool_ipv6_method
source_config_network_networkmanager_static_ip_example_sh --> tool_nmcli
source_config_network_networkmanager_static_ip_local_sh --> tool_ipv6_method
source_config_network_networkmanager_static_ip_local_sh --> tool_nmcli
source_scripts_build_filebrowser_fork_image_sh --> tool_args
source_scripts_build_filebrowser_fork_image_sh --> tool_cat
source_scripts_build_filebrowser_fork_image_sh --> tool_podman
source_scripts_build_filebrowser_fork_image_sh --> tool_rm
source_scripts_debug_private_access_sh --> tool_tool_443
source_scripts_debug_private_access_sh --> tool_tool_445
source_scripts_debug_private_access_sh --> tool_tool_80
source_scripts_debug_private_access_sh --> tool_bash
source_scripts_debug_private_access_sh --> tool_cat
source_scripts_debug_private_access_sh --> tool_dig
source_scripts_debug_private_access_sh --> tool_docker_compose
source_scripts_debug_private_access_sh --> tool_grep
source_scripts_debug_private_access_sh --> tool_host
source_scripts_debug_private_access_sh --> tool_id
source_scripts_debug_private_access_sh --> tool_mkdir
source_scripts_debug_private_access_sh --> tool_sed
source_scripts_deploy_filebrowser_fork_image_sh --> tool_args_container_tool
source_scripts_deploy_filebrowser_fork_image_sh --> tool_cat
source_scripts_deploy_filebrowser_fork_image_sh --> tool_install
source_scripts_deploy_filebrowser_fork_image_sh --> tool_next
source_scripts_deploy_filebrowser_fork_image_sh --> tool_print
source_scripts_deploy_filebrowser_fork_image_sh --> tool_private_vpn
source_scripts_deploy_filebrowser_fork_image_sh --> tool_private_vpn_mtls
source_scripts_deploy_filebrowser_fork_image_sh --> tool_public
source_scripts_deploy_filebrowser_fork_image_sh --> tool_rm
source_scripts_deploy_filebrowser_fork_image_sh --> tool_updated
source_scripts_remount_luks_share_sh --> tool_mapfile
source_scripts_remount_luks_share_sh --> tool_mount
source_scripts_remount_luks_share_sh --> tool_umount
source_scripts_run_tachometer_profile_sh --> tool_run
source_scripts_run_tachometer_profile_sh --> tool_summarize
source_scripts_run_tachometer_profile_sh --> tool_tachometer
source_scripts_setup_caddy_filebrowser_sh --> tool_in_global
source_scripts_setup_caddy_filebrowser_sh --> tool_command_exists
source_scripts_setup_caddy_filebrowser_sh --> tool_tool_2_0_9
source_scripts_setup_caddy_filebrowser_sh --> tool_tool_3_0_1
source_scripts_setup_caddy_filebrowser_sh --> tool_space
source_scripts_setup_caddy_filebrowser_sh --> tool_space_2
source_scripts_setup_caddy_filebrowser_sh --> tool_apt_get
source_scripts_setup_caddy_filebrowser_sh --> tool_cat
source_scripts_setup_caddy_filebrowser_sh --> tool_chmod
source_scripts_setup_caddy_filebrowser_sh --> tool_dnf
source_scripts_setup_caddy_filebrowser_sh --> tool_docker
source_scripts_setup_caddy_filebrowser_sh --> tool_docker_compose
source_scripts_setup_caddy_filebrowser_sh --> tool_docker_compose_2
source_scripts_setup_caddy_filebrowser_sh --> tool_grep
source_scripts_setup_caddy_filebrowser_sh --> tool_host
source_scripts_setup_caddy_filebrowser_sh --> tool_i
source_scripts_setup_caddy_filebrowser_sh --> tool_in_global_2
source_scripts_setup_caddy_filebrowser_sh --> tool_install
source_scripts_setup_caddy_filebrowser_sh --> tool_mv
source_scripts_setup_caddy_filebrowser_sh --> tool_next
source_scripts_setup_caddy_filebrowser_sh --> tool_podman_compose
source_scripts_setup_caddy_filebrowser_sh --> tool_print
source_scripts_setup_caddy_filebrowser_sh --> tool_private_vpn
source_scripts_setup_caddy_filebrowser_sh --> tool_private_vpn_mtls
source_scripts_setup_caddy_filebrowser_sh --> tool_public
source_scripts_setup_caddy_filebrowser_sh --> tool_rm
source_scripts_setup_caddy_filebrowser_sh --> tool_site
source_scripts_setup_caddy_filebrowser_sh --> tool_split_site
source_scripts_setup_caddy_filebrowser_sh --> tool_tr
source_scripts_setup_caddy_filebrowser_sh --> tool_update_ca_certificates
source_scripts_setup_caddy_filebrowser_sh --> tool_update_ca_trust
source_scripts_setup_caddy_filebrowser_sh --> tool_yum
source_scripts_setup_filebrowser_fork_workspace_sh --> tool_major
source_scripts_setup_filebrowser_fork_workspace_sh --> tool_cat
source_scripts_setup_filebrowser_fork_workspace_sh --> tool_golang_go
source_scripts_setup_filebrowser_fork_workspace_sh --> tool_ln
source_scripts_setup_filebrowser_fork_workspace_sh --> tool_minor
source_scripts_setup_filebrowser_fork_workspace_sh --> tool_node
source_scripts_setup_filebrowser_fork_workspace_sh --> tool_rm
source_scripts_setup_wireguard_endpoint_monitor_sh --> tool_cat
source_scripts_setup_wireguard_endpoint_monitor_sh --> tool_install
source_scripts_setup_wireguard_endpoint_monitor_sh --> tool_systemctl
source_scripts_start_snowbridge_sh --> tool_bash
source_scripts_start_snowbridge_sh --> tool_docker_compose
source_scripts_start_snowbridge_sh --> tool_grep
source_scripts_start_snowbridge_sh --> tool_ip
source_scripts_start_snowbridge_sh --> tool_nordvpn
source_scripts_start_snowbridge_sh --> tool_systemctl
source_scripts_start_snowbridge_sh --> tool_up
source_scripts_start_snowbridge_sh --> tool_wg
source_vendor_filebrowser_upstream_dockerfile --> tool_addgroup
source_vendor_filebrowser_upstream_dockerfile --> tool_adduser
source_vendor_filebrowser_upstream_dockerfile --> tool_apk
source_vendor_filebrowser_upstream_dockerfile --> tool_chmod
source_vendor_filebrowser_upstream_dockerfile --> tool_chown
source_vendor_filebrowser_upstream_dockerfile --> tool_docker
source_vendor_filebrowser_upstream_dockerfile --> tool_mkdir
source_vendor_filebrowser_upstream_dockerfile --> tool_wget
source_vendor_filebrowser_upstream_dockerfile_s6 --> tool_apk
source_vendor_filebrowser_upstream_dockerfile_s6 --> tool_chown
source_vendor_filebrowser_upstream_dockerfile_s6 --> tool_docker
source_vendor_filebrowser_upstream_dockerfile_s6 --> tool_mkdir
source_vendor_filebrowser_upstream_dockerfile_s6 --> tool_setcap
source_vendor_filebrowser_upstream_taskfile_yml --> tool_cli
source_vendor_filebrowser_upstream_taskfile_yml --> tool_docker
source_vendor_filebrowser_upstream_taskfile_yml --> tool_git
source_vendor_filebrowser_upstream_taskfile_yml --> tool_go
source_vendor_filebrowser_upstream_taskfile_yml --> tool_mkdir
source_vendor_filebrowser_upstream_taskfile_yml --> tool_pnpm
source_vendor_filebrowser_upstream_taskfile_yml --> tool_rm
source_vendor_filebrowser_upstream_compose_yaml --> tool_docker_compose
source_vendor_filebrowser_upstream_docker_alpine_healthcheck_sh --> tool_awk
source_vendor_filebrowser_upstream_docker_alpine_healthcheck_sh --> tool_grep
source_vendor_filebrowser_upstream_docker_alpine_healthcheck_sh --> tool_sed
source_vendor_filebrowser_upstream_docker_alpine_healthcheck_sh --> tool_settings_json
source_vendor_filebrowser_upstream_docker_alpine_healthcheck_sh --> tool_sh
source_vendor_filebrowser_upstream_docker_alpine_healthcheck_sh --> tool_wget
source_vendor_filebrowser_upstream_docker_alpine_init_sh --> tool_cp
source_vendor_filebrowser_upstream_docker_common_healthcheck_sh --> tool_wget
source_vendor_filebrowser_upstream_docker_s6_custom_cont_init_d_20_config --> tool_cp
source_vendor_filebrowser_upstream_docker_s6_custom_cont_init_d_20_config --> tool_srv
source_vendor_filebrowser_upstream_www_dockerfile --> tool_docker
source_vendor_filebrowser_upstream_www_dockerfile --> tool_pip
note as toolingGraphSummary
Scanned 25 tooling entrypoints.
Detected 82 third-party tools.
end note
@enduml
